clone:
  path: github.com/udistrital/update_tuleap

build:
  pruebas_unitarias:
    image: golang:1.8
    debug: true
    commands:
      - go test -v ./...
    when:
      branch: develop

  construccion:
    image: golang:1.8
    commands:
      - mkdir -p target
      - GOOS=linux GOARCH=amd64 go build -o target/update-tuleap-$${COMMIT:0:7}-linux-x86_64
      - GOOS=windows GOARCH=amd64 go build -o target/update-tuleap-$${COMMIT:0:7}-windows-x86_64.exe
      - GOOS=darwin GOARCH=amd64 go build -o target/update-tuleap-$${COMMIT:0:7}-darwin-x86_64
    when:
      branch: master

publish:
  sftp:
    host: nas03.udistritaloas.edu.co
    port: 22
    username: drone
    password: $$DRONE_NAS_PASSWORD
    destination_path: /share/artifacts/golang
    files:
      - target/*
    when:
      branch: master

notify:
  webhook:
    urls:
      - https://api.telegram.org/bot$$DRONE_TELEGRAM_TOKEN/sendMessage
    content_type: application/json
    template: >
      {
        "chat_id": "-130629599",
        "parse_mode": "Markdown",
        "text": "`{{repo.full_name}}` [{{uppercase build.status}}]({{build.link_url}}) `{{build.branch}}`@{{truncate build.commit 7}}"
      }
