clone:
  path: github.com/udistrital/update_tuleap

build:
  pruebas_unitarias:
    image: golang:1.8
    debug: true
    commands:
      - go test -v ./...
    when:
      branch: develop

  construccion:
    image: golang:1.8
    commands:
      - mkdir -p "target/update_tuleap/$${COMMIT:0:7}"
      - GOOS=linux GOARCH=amd64 go build -o "target/update_tuleap/$${COMMIT:0:7}/update-tuleap-linux-x86_64"
      - GOOS=windows GOARCH=amd64 go build -o "target/update_tuleap/$${COMMIT:0:7}/update-tuleap-windows-x86_64.exe"
      - GOOS=darwin GOARCH=amd64 go build -o "target/update_tuleap/$${COMMIT:0:7}/update-tuleap-darwin-x86_64"
    when:
      branch: master

publish:
  sftp:
    host: nas03.udistritaloas.edu.co
    port: 22
    username: drone
    password: $$DRONE_NAS_PASSWORD
    destination_path: "/share/artifacts"
    files:
      - target/update_tuleap
    when:
      branch: master
